apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: release-go-web-service-ingress
  namespace: team-blue-dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: a0fc3bd3dfc18437fac19d7b86570e7e-1254250968.eu-west-2.elb.amazonaws.com
      http:
        paths:
          - backend:
              service: 
                name: go-web-service
                port: 
                  number: 80
            path: /
            pathType: Prefix
