apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: addons-argo
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/warrenwb/blueprints_workloads.git
    targetRevision: main
    path: addons/argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
