apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: job-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: job-operator
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/warrenwb/onclusive-job.git
    targetRevision: main
    path: job-operator/operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true
